#!/usr/bin/env python
#-*- coding: utf-8 -*-

import argparse

from scriptalib import density_plot, latex_mode

if __name__ == "__main__":
    # Parse arguments
    parser = argparse.ArgumentParser(
        description="Plot a graph edgelist to an adjacency matrix.",
    )
    parser.add_argument(
        'f',
        help="Input file",
    )
    parser.add_argument(
        'o',
        type=str,
        help="Output file",
    )
    args = parser.parse_args()

    infile = args.f
    outfile = args.o
    latex_mode()
    density_plot(infile, outfile)
