#!/usr/bin/env python
#-*- coding: utf-8 -*-

"""
Convert a matrix in edgelist form to a matrix in adjacencjy matrix form.
"""

import argparse
import sys

from scriptalib import skip_lines, read_edgelist, write_matrix

if __name__ == "__main__":
    # Parse arguments
    parser = argparse.ArgumentParser(
        description="Convert a graph edgelist to an adjacency matrix.",
    )
    parser.add_argument(
        '-f',
        type=argparse.FileType('r'),
        default=sys.stdin,
        help="Input file (default stdin)",
    )
    parser.add_argument(
        '-o',
        type=argparse.FileType('w'),
        default=sys.stdout,
        help="Output file (default stdout)",
    )
    parser.add_argument('-skip', help="Skip first N lines", type=int, default=0)
    parser.add_argument('-oneindex', help="Edgelist indexes start from 1",
            default=False)
    args = parser.parse_args()

    infile = args.f
    outfile = args.o
    skip_lines(infile, args.skip)
    arr = read_edgelist(infile)
    write_matrix(arr, args.o) 
